name: Build and Release (tags)

on:
  push:
    tags:
      - "v*.*.*" # triggers on tags like v1.0.0

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js with specific npm
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: "npm"
          check-latest: true
      - run: npm install -g npm@11.2.0 # Pin exact npm version

      - name: Install dependencies
        run: npm ci

      - name: Build and publish to GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # built-in token
        run: npm run dist:publish
